### ISSUE TITLE
Failed to load the atom-ide-golang package

### ISSUE THREAD

**Issue by zonieedhossain** [Atrociously/atom-ide-golang#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 18.04.5
**Thrown From**: [atom-ide-golang](https://github.com/Atrociously/atom-ide-golang) package 0.1.1

### Stack Trace

Failed to load the atom-ide-golang package

```
At Cannot find module 'atom-ts-transpiler' from '/home/torque/.atom/packages/atom-ide-golang'

Error: Cannot find module 'atom-ts-transpiler' from '/home/torque/.atom/packages/atom-ide-golang'
    at /app.asar/node_modules/resolve/lib/sync.js:89:15)
    at PackageTranspilationRegistry.getTranspilerPath (/usr/share/atom/resources/app/static/<embedded>:11:577258)
    at PackageTranspilationRegistry.getCachePath (/usr/share/atom/resources/app/static/<embedded>:11:576213)
    at Object.getCachePath (/usr/share/atom/resources/app/static/<embedded>:11:575300)
    at compileFileAtPath (/usr/share/atom/resources/app/static/<embedded>:11:148336)
    at Object.value [as .ts] (/usr/share/atom/resources/app/static/<embedded>:11:150918)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:696986)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3517326)
    at /usr/share/atom/resources/app/static/<embedded>:11:3503866
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3502666)
    at Package.load (/usr/share/atom/resources/app/static/<embedded>:11:3503439)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/static/<embedded>:11:382181)
    at /usr/share/atom/resources/app/static/<embedded>:11:380604
    at Config.transact (/usr/share/atom/resources/app/static/<embedded>:11:332567)
    at PackageManager.loadPackages (/usr/share/atom/resources/app/static/<embedded>:11:380542)
    at /usr/share/atom/resources/app/static/<embedded>:1:717613
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app/static/<embedded>:1:719652)
```

### Commands

```
     -0:00.8.0 golang:update-tools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-golang 0.1.1 
atom-ide-ui 0.13.0 
atom-json 0.6.0 
atom-mysql-snippets 0.3.1 
autocomplete-sql 0.5.0 
docker 0.8.0 
go-build 0.2.2 
go-debug 1.7.0 
go-oracle 0.2.1 
go-outline 0.6.11 
go-plus 6.1.0 
go-quick-import 0.3.1 
go-signature-statusbar 1.2.3 
go-types 1.2.1 
ide-docker 0.1.0 
ide-go 0.12.3 
ide-golang 0.0.5 
ide-json 0.2.1 
import-it 1.0.1 
language-sql-mysql 0.3.1 
linter-golinter 1.3.0 
quick-query 1.1.1 
```

**Comment by Atrociously** [comment]
Thanks for letting me know about this, thankfully this was an easy fix and is now published in the latest 0.1.2 update! If you still experience more issues let me know!
