### ISSUE TITLE
SyntaxError: Unexpected token: Extension crashes in startup

### ISSUE THREAD

**Issue by luckcolors** [Atrociously/atom-ide-golang#2]
Hello.
I've been trying to use your extension to use golang with atom.
I cannot seem to get it to work however this is the stack trace i get.

I do have both required exstensions `go-plus` and `atom-ide-iu` installed.
Atom version: 1.54.0

```
atom-ide-golang\lib\main.ts:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import { GoLanguageClient } from './go-languageclient'
                                                                                                                                                                  ^
SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at NativeCompileCache.runInThisContext (atom\app-1.54.0\resources\app\static\<embedded>:11:146297)
    at Module.get_Module._compile (atom\app-1.54.0\resources\app\static\<embedded>:11:147181)
    at Object.value [as .ts] (atom\app-1.54.0\resources\app\static\<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (file:///atom/app-1.54.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (atom\app-1.54.0\resources\app\static\<embedded>:1:723602)
    at Package.requireMainModule (atom\app-1.54.0\resources\app\static\<embedded>:11:3670531)
    at atom\app-1.54.0\resources\app\static\<embedded>:11:3657071
    at Package.measure (atom\app-1.54.0\resources\app\static\<embedded>:11:3655871)
    at Package.load (atom\app-1.54.0\resources\app\static\<embedded>:11:3656644)
    at PackageManager.loadAvailablePackage (atom\app-1.54.0\resources\app\static\<embedded>:11:382220)
    at atom\app-1.54.0\resources\app\static\<embedded>:11:380643
    at Config.transact (atom\app-1.54.0\resources\app\static\<embedded>:11:332606)
    at PackageManager.loadPackages (atom\app-1.54.0\resources\app\static\<embedded>:11:380581)
    at atom\app-1.54.0\resources\app\static\<embedded>:1:744229
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (atom\app-1.54.0\resources\app\static\<embedded>:1:746268)
```

**Comment by Atrociously** [comment]
This is an issue that keeps popping up due to typescript transpiling into javascript I was able to reproduce the error but when I reloaded atom the plugin worked. I will continue work on solving this issue please let me know it the package work or not with the newest update and after reloading.
